# Model Training and Evaluation

This notebook trains and evaluates multiple classification models for predicting customer churn.

Models:
- Logistic Regression
- K-Nearest Neighbors (KNN)
- Decision Tree
- Random Forest
- Gradient Boosting

Evaluation Metrics:
- Accuracy
- Precision
- Recall
- F1 Score
- ROC-AUC

In [6]:
import pandas as pd 
import numpy as np
import joblib
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, classification_report
from xgboost import XGBClassifier

In [7]:
# Load data

df = pd.read_csv("../data/Telco-Customer-Churn.csv")

In [8]:
# convert TotalCharges and drop the null val

df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")
df = df.dropna()

In [9]:
# drop customer id
df = df.drop("customerID", axis=1)

In [10]:
# create features and target
X = df.drop("Churn", axis=1)
y = df["Churn"].map({"Yes":1, "No":0})

In [11]:
# One-hot encoding

X = pd.get_dummies(X, drop_first=True)

In [12]:
# split 

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [13]:
# scaling

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

## model 1: Logistic Regression

In [14]:
lr = LogisticRegression(random_state=42,
    class_weight="balanced")

lr.fit(X_train_scaled, y_train)

y_pred_lr = lr.predict(X_test_scaled)

In [15]:
acc_lr = accuracy_score(y_test, y_pred_lr)
prec_lr = precision_score(y_test, y_pred_lr)
rec_lr = recall_score(y_test,y_pred_lr)
f1_lr = f1_score(y_test, y_pred_lr)
roc_lr = roc_auc_score(y_test, y_pred_lr)

print("Accuracy : ", acc_lr)
print("precision : ", prec_lr )
print("Recall : ", rec_lr )
print("F1_score : ", f1_lr)
print("ROC-AUC", roc_lr)


Accuracy :  0.7263681592039801
precision :  0.49093904448105435
Recall :  0.7967914438502673
F1_score :  0.6075433231396534
ROC-AUC 0.7488313463200998


## model 2: K-Nearest Neighbors (KNN)

In [16]:
knn = KNeighborsClassifier()

knn.fit(X_train_scaled, y_train)

y_pred_knn = knn.predict(X_test_scaled)

In [17]:
acc_knn = accuracy_score(y_test, y_pred_knn)
prec_knn = precision_score(y_test, y_pred_knn)
rec_knn = recall_score(y_test,y_pred_knn)
f1_knn = f1_score(y_test, y_pred_knn)
roc_knn = roc_auc_score(y_test, y_pred_knn)

print("Accuracy : ", acc_knn)
print("precision : ", prec_knn )
print("Recall : ", rec_knn )
print("F1_score : ", f1_knn)
print("ROC-AUC", roc_knn)

Accuracy :  0.7533759772565742
precision :  0.5361930294906166
Recall :  0.5347593582887701
F1_score :  0.535475234270415
ROC-AUC 0.6836429898897867


## Model 3: Decision Tree

In [18]:
dt = DecisionTreeClassifier(random_state=42, max_depth=5)

dt.fit(X_train, y_train)

y_pred_dt = dt.predict(X_test)

In [19]:
acc_dt = accuracy_score(y_test, y_pred_dt)
prec_dt = precision_score(y_test, y_pred_dt)
rec_dt = recall_score(y_test,y_pred_dt)
f1_dt = f1_score(y_test, y_pred_dt)
roc_dt = roc_auc_score(y_test, y_pred_dt)

print("Accuracy : ", acc_dt)
print("precision : ", prec_dt )
print("Recall : ", rec_dt )
print("F1_score : ", f1_dt)
print("ROC-AUC", roc_dt)

Accuracy :  0.7782515991471215
precision :  0.5807291666666666
Recall :  0.5962566844919787
F1_score :  0.5883905013192612
ROC-AUC 0.720199978257606


## Model 4: Random Forest

In [20]:
rf = RandomForestClassifier(random_state=42, n_estimators=100)

rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)

In [21]:
acc_rf = accuracy_score(y_test, y_pred_rf)
prec_rf = precision_score(y_test, y_pred_rf)
rec_rf = recall_score(y_test,y_pred_rf)
f1_rf = f1_score(y_test, y_pred_rf)
roc_rf = roc_auc_score(y_test, y_pred_rf)

print("Accuracy : ", acc_rf)
print("precision : ", prec_rf )
print("Recall : ", rec_rf )
print("F1_score : ", f1_rf)
print("ROC-AUC", roc_rf)

Accuracy :  0.7896233120113717
precision :  0.6258064516129033
Recall :  0.5187165775401069
F1_score :  0.5672514619883041
ROC-AUC 0.703211144529976


## Model 5: Gradient Boosting

In [22]:
gb = GradientBoostingClassifier(random_state=42, n_estimators=100, learning_rate=0.1)

gb.fit(X_train, y_train)

y_pred_gb = gb.predict(X_test)

In [23]:
acc_gb = accuracy_score(y_test, y_pred_gb)
prec_gb = precision_score(y_test, y_pred_gb)
rec_gb = recall_score(y_test,y_pred_gb)
f1_gb = f1_score(y_test, y_pred_gb)
roc_gb = roc_auc_score(y_test, y_pred_gb)

print("Accuracy : ", acc_gb)
print("precision : ", prec_gb )
print("Recall : ", rec_gb )
print("F1_score : ", f1_gb)
print("ROC-AUC", roc_gb)

Accuracy :  0.7953091684434968
precision :  0.6378205128205128
Recall :  0.5320855614973262
F1_score :  0.5801749271137027
ROC-AUC 0.7113477178251395


In [24]:
results = pd.DataFrame({

    "Model":[
        "Logistic Regression",
        "KNN",
        "Decision Tree",
        "Random Forest",
        "Gradient Boosting"
    ],
    "Accuracy": [
        acc_lr,
        acc_knn,
        acc_dt,
        acc_rf,
        acc_gb

    ],
        "precision": [
        prec_lr,
        prec_knn,
        prec_dt,
        prec_rf,
        prec_gb

    ],  
      
        "Recall": [
       rec_lr,
       rec_knn,
       rec_dt,
       rec_rf,
       rec_gb

    ],  
      
        "F1_score": [
        f1_lr,
        f1_knn,
        f1_dt,
        f1_rf,
        f1_gb

    ],  
      
        "ROC-AUC": [
        roc_lr,
        roc_knn,
        roc_dt,
        roc_rf,
        roc_gb

    ]
})

results.sort_values(by="F1_score", ascending=False)

,Model,Accuracy,precision,Recall,F1_score,ROC-AUC
0,Logistic Regression,0.726368,0.490939,0.796791,0.607543,0.748831
2,Decision Tree,0.778252,0.580729,0.596257,0.588391,0.720200
4,Gradient Boosting,0.795309,0.637821,0.532086,0.580175,0.711348
3,Random Forest,0.789623,0.625806,0.518717,0.567251,0.703211
1,KNN,0.753376,0.536193,0.534759,0.535475,0.683643


In [36]:
confusion_matrix(y_test, y_pred_lr)

array([[724, 309],
       [ 76, 298]])

In [ ]:
model = joblib.dump(lr, "../models/churn_model.pkl")
scaler = joblib.dump(scaler, "../models/scaler.pkl")
model_columns = joblib.dump(X.columns.tolist(), "../models/model_columns.pkl")

In [28]:
model_columns = joblib.load("../models/model_columns.pkl")

feature_importance = pd.DataFrame({
    "feature": model_columns,
    "coef": lr.coef_[0]
}).sort_values(by="coef", ascending=False)

In [29]:
feature_importance = pd.DataFrame({
    "feature": model_columns,
    "coef": lr.coef_[0]
}).sort_values(by="coef", ascending=False)

feature_importance

,feature,coef
10,InternetService_Fiber optic,0.746144
3,TotalCharges,0.623279
21,StreamingTV_Yes,0.259691
23,StreamingMovies_Yes,0.252870
9,MultipleLines_Yes,0.202763
28,PaymentMethod_Electronic check,0.193697
26,PaperlessBilling_Yes,0.124250
0,SeniorCitizen,0.075306
17,DeviceProtection_Yes,0.069476
27,PaymentMethod_Credit card (automatic),0.029226


In [31]:
xgb = XGBClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=4,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    eval_metric="logloss"
)

xgb.fit(X_train, y_train)

,"base_score base_score: typing.Union[float, typing.List[float], NoneType]The initial prediction score of all instances, global bias.",None
,booster,None
,"callbacks callbacks: typing.Optional[typing.List[xgboost.callback.TrainingCallback]]List of callback functions that are applied at end of each iteration.It is possible to use predefined callbacks by using:ref:`Callback API <callback_api>`... note:: States in callback are not preserved during training, which means callback objects can not be reused for multiple training sessions without reinitialization or deepcopy... code-block:: python for params in parameters_grid: # be sure to (re)initialize the callbacks before each run callbacks = [xgb.callback.LearningRateScheduler(custom_rates)] reg = xgboost.XGBRegressor(**params, callbacks=callbacks) reg.fit(X, y)",None
,colsample_bylevel colsample_bylevel: typing.Optional[float]Subsample ratio of columns for each level.,None
,colsample_bynode colsample_bynode: typing.Optional[float]Subsample ratio of columns for each split.,None
,colsample_bytree colsample_bytree: typing.Optional[float]Subsample ratio of columns when constructing each tree.,0.8
,"device device: typing.Optional[str].. versionadded:: 2.0.0Device ordinal, available options are `cpu`, `cuda`, and `gpu`.",None
,"early_stopping_rounds early_stopping_rounds: typing.Optional[int].. versionadded:: 1.6.0- Activates early stopping. Validation metric needs to improve at least once in every **early_stopping_rounds** round(s) to continue training. Requires at least one item in **eval_set** in :py:meth:`fit`.- If early stopping occurs, the model will have two additional attributes: :py:attr:`best_score` and :py:attr:`best_iteration`. These are used by the :py:meth:`predict` and :py:meth:`apply` methods to determine the optimal number of trees during inference. If users want to access the full model (including trees built after early stopping), they can specify the `iteration_range` in these inference methods. In addition, other utilities like model plotting can also use the entire model.- If you prefer to discard the trees after `best_iteration`, consider using the callback function :py:class:`xgboost.callback.EarlyStopping`.- If there's more than one item in **eval_set**, the last entry will be used for early stopping. If there's more than one metric in **eval_metric**, the last metric will be used for early stopping.",None
,enable_categorical enable_categorical: boolSee the same parameter of :py:class:`DMatrix` for details.,False
,"eval_metric eval_metric: typing.Union[str, typing.List[typing.Union[str, typing.Callable]], typing.Callable, NoneType].. versionadded:: 1.6.0Metric used for monitoring the training result and early stopping. It can be astring or list of strings as names of predefined metric in XGBoost (See:doc:`/parameter`), one of the metrics in :py:mod:`sklearn.metrics`, or anyother user defined metric that looks like `sklearn.metrics`.If custom objective is also provided, then custom metric should implement thecorresponding reverse link function.Unlike the `scoring` parameter commonly used in scikit-learn, when a callableobject is provided, it's assumed to be a cost function and by default XGBoostwill minimize the result during early stopping.For advanced usage on Early stopping like directly choosing to maximize insteadof minimize, see :py:obj:`xgboost.callback.EarlyStopping`.See :doc:`/tutorials/custom_metric_obj` and :ref:`custom-obj-metric` for moreinformation... code-block:: python from sklearn.datasets import load_diabetes from sklearn.metrics import mean_absolute_error X, y = load_diabetes(return_X_y=True) reg = xgb.XGBRegressor( tree_method=""hist"", eval_metric=mean_absolute_error, ) reg.fit(X, y, eval_set=[(X, y)])",'logloss'
,feature_types feature_types: typing.Optional[typing.Sequence[str]].. versionadded:: 1.7.0Used for specifying feature types without constructing a dataframe. Seethe :py:class:`DMatrix` for details.,None


In [32]:
y_pred_xgb = xgb.predict(X_test)
y_prob_xgb = xgb.predict_proba(X_test)[:,1]

In [33]:
acc_xgb = accuracy_score(y_test, y_pred_xgb)
prec_xgb = precision_score(y_test,y_pred_xgb)
rec_xgb = recall_score(y_test, y_pred_xgb)
f1_xgb = f1_score(y_test, y_pred_xgb)
roc_xgb = roc_auc_score(y_test, y_pred_xgb)

print("Accuracy: ", acc_xgb)
print("Precision: ", prec_xgb)
print("Recall: ", rec_xgb)
print("F1: ", f1_xgb)
print("ROC-AUC: ", roc_xgb)

Accuracy:  0.7839374555792467
Precision:  0.610062893081761
Recall:  0.5187165775401069
F1:  0.5606936416184971
ROC-AUC:  0.6993389276858327


In [34]:
threshold = 0.35
y_pred_thresh = (y_prob_xgb >= threshold).astype(int)
classificationReport = classification_report(y_test, y_pred_thresh)
print(classificationReport)

              precision    recall  f1-score   support

           0       0.89      0.78      0.83      1033
           1       0.55      0.73      0.63       374

    accuracy                           0.77      1407
   macro avg       0.72      0.76      0.73      1407
weighted avg       0.80      0.77      0.78      1407



In [35]:
confusion_matrix(y_test, y_pred_xgb)

array([[909, 124],
       [180, 194]])

In [37]:
y_pred_xgb = (y_prob_xgb >= 0.30).astype(int)

In [38]:
confusion_matrix(y_test, y_pred_xgb)

array([[764, 269],
       [ 87, 287]])

In [81]:
joblib.dump(xgb, "../models/churn_model.pkl")
joblib.dump(scaler, "../models/scaler.pkl")
joblib.dump(X.columns.tolist(), "../models/model_columns.pkl")

['../models/model_columns.pkl']

In [75]:
model = joblib.load("../models/churn_model.pkl")
scaler = joblib.load("../models/scaler.pkl")
model_columns = joblib.load("../models/model_columns.pkl")

In [49]:
len(model_columns)

30

In [50]:
input_data = pd.DataFrame({
    "gender": ["Female"],
    "SeniorCitizen": [1],
    "Partner": ["No"],
    "Dependents": ["No"],
    "tenure": [2],
    "PhoneService": ["Yes"],
    "MultipleLines": ["Yes"],
    "InternetService": ["Fiber optic"],
    "OnlineSecurity": ["No"],
    "OnlineBackup": ["No"],
    "DeviceProtection": ["No"],
    "TechSupport": ["No"],
    "StreamingTV": ["Yes"],
    "StreamingMovies": ["Yes"],
    "Contract": ["Month-to-month"],
    "PaperlessBilling": ["Yes"],
    "PaymentMethod": ["Electronic check"],
    "MonthlyCharges": [120.0],
    "TotalCharges": [120.0]
})

In [51]:
input_data = pd.get_dummies(input_data, drop_first=True)

input_data = input_data.reindex(columns=model_columns, fill_value=0)

In [52]:
input_data.shape[1]

30